### ISSUE TITLE
RPC system error when calling get balanced on governance addresses 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#114]
Don't know if this is something worth looking at or fixing as it is an edge case, but when calling:
```json
{
    "jsonrpc": "2.0",
    "method": "icx_getBalance",
    "id": 1234,
    "params": {
         "address": "hx0000000000000000000000000000000000000000"
    }
}
```

Or on hx0000000000000000000000000000000000000001, I get the following error:

```
Response={"jsonrpc":"2.0","error":{"code":-31000,"message":"SystemError: E1002:InvalidAddressPrefix(valid=cx0000000000000000000000000000000000000000)"},"id":1234}
```

I built in an exception handler in my logic for these addresses but figured I'd raise this as an issue to take note.

**Comment by mksong-icon** [comment]
ID part of hx0000000000000000000000000000000000000000 is 0x0000000000000000000000000000000000000000. And currently, 0x0000000000000000000000000000000000000000 is system contract. So, it should use cx0000000000000000000000000000000000000000 instead of hx0000000000000000000000000000000000000000.
So, it's an expected behavior.

**Comment by robcxyz** [comment]
Thanks @mksong-icon - Yeah I didn't think this was a big issue but figured I'd raise just in case. Thanks for clarification.
